### ISSUE TITLE
Update to "Deploy Custom Docker Image To OKE Cluster"

### ISSUE THREAD

**Issue by KrashLeviathan** [enabling-cloud/oci-learning#4]
Please update your article with this important detail: The image pull secret HAS to be of `type: kubernetes.io/dockerconfigjson`, otherwise you can have everything else right and it still won't read in the credentials. It took me hours to figure this out, because I was creating the manifest file for the secret via a Helm template rather than with the `kubectl create` command.

**Comment by mnadeem** [comment]
please create pull request
